AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Seedhape mock webhook receiver

Globals:
  Function:
    Timeout: 15
    MemorySize: 256
    Runtime: python3.12

Parameters:
  SeedhapeWebhookSecret:
    Type: String
    NoEcho: true

Resources:
  WebhookReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.lambda_handler
      Environment:
        Variables:
          SEEDHAPE_WEBHOOK_SECRET: !Ref SeedhapeWebhookSecret
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST

Outputs:
  WebhookApiUrl:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook
